### ISSUE TITLE
Write a script to scrape all artifact URLs / sha256s from artifactory

### ISSUE THREAD

**Issue by connorworley** [bazelRio/bazelRio#11]
Even better if we can write it in Starlark

**Comment by noamzaks** [comment]
We can get the SHA256 sums from Artifactory (I don't know if it's available at every maven repository, i.e. REV's or CTRE's)
with a simple GET request to a path like https://frcmaven.wpi.edu/api/storage/wpilib-mvn-release/edu/wpi/first/wpilibc/wpilibc-cpp/2021.3.1/wpilibc-cpp-2021.3.1-linuxaarch64bionic.zip.

(This returns
```json
{
  "repo" : "wpilib-mvn-release",
  "path" : "/edu/wpi/first/wpilibc/wpilibc-cpp/2021.3.1/wpilibc-cpp-2021.3.1-linuxaarch64bionic.zip",
  "created" : "2021-04-25T04:45:07.643Z",
  "createdBy" : "austinshalit",
  "lastModified" : "2021-04-25T04:45:07.252Z",
  "modifiedBy" : "austinshalit",
  "lastUpdated" : "2021-04-25T04:45:07.643Z",
  "downloadUri" : "https://frcmaven.wpi.edu/artifactory/wpilib-mvn-release/edu/wpi/first/wpilibc/wpilibc-cpp/2021.3.1/wpilibc-cpp-2021.3.1-linuxaarch64bionic.zip",
  "mimeType" : "application/zip",
  "size" : "13840831",
  "checksums" : {
    "sha1" : "50bff52956ba6ad99134d6f8ae967ff1f33a0074",
    "md5" : "cee9d0fb32f4a25d98b2dccb67c0d67a",
    "sha256" : "bdb98dfe7dea867c667cce39cf936fa1844b3eb6df77df868fbc761334e1e010"
  },
  "originalChecksums" : {
    "sha1" : "50bff52956ba6ad99134d6f8ae967ff1f33a0074",
    "md5" : "cee9d0fb32f4a25d98b2dccb67c0d67a",
    "sha256" : "bdb98dfe7dea867c667cce39cf936fa1844b3eb6df77df868fbc761334e1e010"
  },
  "uri" : "https://frcmaven.wpi.edu/artifactory/api/storage/wpilib-mvn-release/edu/wpi/first/wpilibc/wpilibc-cpp/2021.3.1/wpilibc-cpp-2021.3.1-linuxaarch64bionic.zip"
}
```
)

Unfortunately I couldn't see a way to use the Starlark standard library and `load("http", "get")` into a .bzl file tho.

**Comment by connorworley** [comment]
It's probably fine to generate dependency definitions out-of-band if we can't do it in Starlark

**Comment by noamzaks** [comment]
wdym?

**Comment by noamzaks** [comment]
wdym?

**Comment by connorworley** [comment]
We could write a script outside of Starlark to scrape sha256s / downloadUris from maven and generate relevant http_archive invocations by writing the code to a .bzl file. We'd just have to run it when new versions of things come out.
