### ISSUE TITLE
Update robot-sim-* to robot.simulate.*?

### ISSUE THREAD

**Issue by noamzaks** [bazelRio/bazelRio#28]
This should be more uniform with the `robot.deploy` naming.
What do you think?
@pjreiniger

**Comment by pjreiniger** [comment]
Still @connorworley repo, he should decide. Either way it should be consistent, but he can decide dash vs dot.

**Comment by connorworley** [comment]
The bazel example uses dot, so I think we should go with that: https://docs.bazel.build/versions/main/skylark/tutorial-custom-verbs.html
