### ISSUE TITLE
README version strip_prefix doesn't work

### ISSUE THREAD

**Issue by noamzaks** [bazelRio/bazelRio#65]
Currently, the workflow script updates the README to use the strip_prefix with the v before the version, i.e. bazelRio-v0.1.1.
This isn't the correct strip prefix, which should be bazelRio-0.1.1.

Another solution could be to release tags without the 'v'.

**Comment by noamzaks** [comment]
@connorworley @pjreiniger

**Comment by pjreiniger** [comment]
I like the `v`, but it apparently that goes against [semver](https://semver.org/spec/v2.0.0.html#is-v123-a-semantic-version)

I don't care either way.

**Comment by connorworley** [comment]
let's just remove the v
