### ISSUE TITLE
Document developer mode for Windows

### ISSUE THREAD

**Issue by noamzaks** [bazelRio/bazelRio#84]
We should document the process of solving

```
build-runfiles error: CreateSymbolicLinkW failed:
Bazel needs to create symlinks to build the runfiles tree.
Creating symlinks on Windows requires one of the following:
    1. Bazel is run with administrator privileges.
    2. The system version is Windows 10 Creators Update (1703) or later and developer mode is enabled.
```

**Comment by noamzaks** [comment]
On Windows 11 it is in settings -> Privacy & security -> For developers -> Install apps from any source, including loose files

**Comment by connorworley** [comment]
I'm inclined to rework the deploy script to avoid this altogether. I'll
dump my notes later.

**Comment by connorworley** [comment]
I'm working on a fix on the fix_deploy_runfiles branch.

**Comment by hanwenz8** [comment]
It works!!! Thank you so much
