### ISSUE TITLE
Fix deploys

### ISSUE THREAD

**Issue by noamzaks** [bazelRio/bazelRio#85]
I'm unsure if this a uniquely a 2022 bug on my beta fork, but the robotCommand deployed is invalid.

Instead I change it to simple contain "/home/lvuser/robot" and then it works.

**Comment by connorworley** [comment]
what error are you seeing?

**Comment by noamzaks** [comment]
Haven’t had much time to analyze it.
The RioLog shows the robot code restarting; no other output shows up, then it goes again.

i added a cout print statement before frc StartRobot which got printed, at least.

**Comment by noamzaks** [comment]
I will try to run the bash command via ssh tomorrow

**Comment by noamzaks** [comment]
It seems that running the robotCommand in ssh crashes the rio. 
In any case, why is the wrapper using bash required?

It works well for my team without it.

**Comment by noamzaks** [comment]
No issues now
